### ISSUE TITLE
Getting java.lang.IncompatibleClassChangeError when using IBM Java

### ISSUE THREAD

**Issue by tomerzel87** [TOPdesk/time-transformer-agent#4] opened 2021-02-04 09:45 UTC
Using the following IBM Java on z/OS s390x :
Java(TM) SE Runtime Environment (build 8.0.5.22 - pmz6480sr5fp22-20180919_01(SR5 FP22))                            
IBM J9 VM (build 2.9, JRE 1.8.0 z/OS s390x-64-Bit Compressed References 20180915_397057 (JIT enabled, AOT enabled) 
OpenJ9   - 6c152c2                                                                                                 
OMR      - 15647c3                                                                                                 
IBM      - d734883)                                                                                                

Getting the following exception:
java.lang.IncompatibleClassChangeError: class java/util/EnumMap has conflicting defaults for method putIfAbsent(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;                                                                                                  
 at java.util.stream.StreamOpFlag$MaskBuilder.build(StreamOpFlag.java:424)                                                           
 at java.util.stream.StreamOpFlag.<init>(StreamOpFlag.java:457)                                                                      
 at java.util.stream.StreamOpFlag.<clinit>(StreamOpFlag.java:259)                                                                    
 at java.util.stream.StreamSupport.stream(StreamSupport.java:81)                                                                     
 at java.util.Collection.stream(Collection.java:592)

**Comment by JoepWeijers** [comment] 2021-02-07 21:15
Hi Tomer, unfortunately I don't have access to a z/OS environment, nor have you provided a [Short, Self Contained, Correct Example](http://sscce.org/) to reproduce the issue.

The only advise I can give you now is updating your Java version if possible and trying again. The IBM 8.0.5.22 is based on Java 8u181 which was released in July 2018.

**Comment by JoepWeijers** [comment] 2022-02-25 14:47
Closing due to no activity

**Closed by JoepWeijers** 2022-02-25 14:47 UTC
